services:
  web:
    image: whojoo/benchmark-dapper-vs-efcore:latest
    deploy:
      resources:
        limits:
          memory: 256m
          cpus: 0.5
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      ConnectionStrings__Vehicle: "Data Source=db,1433;Initial Catalog=DapperVsEfCore;User Id=sa;Password=q1w2e3r4T%;TrustServerCertificate=True"

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "q1w2e3r4T%"
    ports:
      - "1433:1433"